<<<<<<< HEAD
spring:  
  datasource: 
    url: jdbc:mysql://localhost:3306/inmobiliaria?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: Tsernotopulos1
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie
=======
spring:  
  datasource: 
    url: jdbc:mysql://localhost:3306/inmobiliaria?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie
>>>>>>> 4112ebde9bbb6693ac4c29cada6339742ac972f1
  port: 8080